spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      concurrency: 1
    producer:
      acks: -1
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#Minio
minio:
  url: http://localhost:9000
  access:
    key: e106
    secret: password
  bucket-name: images

#Elasticsearch
elasticsearch:
  host-and-port: localhost:9200
  username: elastic
  password: mung1234!@

#Redis
redis:
  server: localhost
  port: 6379

#Tomcat
server:
  tomcat:
    max-http-form-post-size: 100MB

logging:
  level:
    org.elasticsearch: TRACE
    org.elasticsearch.client.RestClient: TRACE
    org.springframework.data.elasticsearch.core: TRACE
    org.springframework.security: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.web.socket.handler: DEBUG
    org.springframework.kafka: ERROR
    org.apache.kafka: ERROR

mungple:
  creation-threshold : 3