spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  kafka:
    bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
    producer:
      acks: -1

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#Minio
minio:
  url: http://localhost:9000
  access:
    key: e106
    secret: password
  bucket-name: images

#Elasticsearch
elasticsearch:
  host-and-port: localhost:9200
  username: elastic
  password: mung1234!@

#Redis
redis:
  server: localhost
  port: 6379

#Tomcat
server:
  tomcat:
    max-http-form-post-size: 100MB

mungple:
  creation-threshold: 3

chaos:
  monkey:
    enabled: true
    watcher:
      service: true
    assaults:
      latencyActive: true

  endpoints:
    web:
      exposure:
        include: "*"
#        include:
#          - health
#          - info
#          - chaosmonkey